### PR TITLE
Add info link to the sidebar

### PR DESCRIPTION
**Pull request by mvdegtyar**

### CODE REVIEW

**Comment by quentincaffeino** [comment]
- spacing around a list of links should be `.p-l` (32px)
- link text should have class `.body-bold`

image

**Comment by quentincaffeino** [comment]
per [design system](https://www.figma.com/file/4y7bPKJ0Ge98PQtaQ8wwGA/Mv%C5%A0-Design-system?node-id=51%3A79) links should have a background when activated

image

**Review by stefanides — APPROVED** [review]
This looks fine to me

**Review by klarasch — APPROVED** [review]
good by me, too! :)

**Pull request merged**
